" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
	filetype plugin indent on
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif " remember place
endif


" strip trailing whitespace when saving
autocmd BufWritePre * %s/\s\+$//e


"colorscheme solarized


syntax enable


set number "set all line numbers
set relativenumber "lines relatively numbered from current
set tabstop=4
set shiftwidth=4
set expandtab
set showmatch		" Show matching brackets.
set hlsearch
set ignorecase		" Do case insensitive matching
set smartcase
set scrolloff=50
set history=1000
set mouse=c
set lazyredraw
set ttyfast
set foldmethod=syntax
set backspace=indent,eol,start
set clipboard=unnamedplus
set autoindent
set smartindent
set pastetoggle=<F2>
set shiftround
set incsearch		" Incremental search
set viminfo+=n~/.vim/viminfo
set tags=./tags;$HOME
set completeopt=menuone,preview
"set colorcolumn=80


hi Folded ctermfg=black
hi CursorLine ctermbg=16
hi CursorColumn ctermfg=9 ctermbg=17


" J and K insert newlines above and below
nnoremap <C-J> o<Esc>
nnoremap <C-K> O<Esc>

" <Leader>c turns on cursor tracking
nnoremap <Leader>c :set cursorcolumn! cursorline!<CR>


""vim-plug calls
call plug#begin()
"Plug 'https://github.com/scrooloose/syntastic.git'
"Plug 'https://github.com/vim-airline/vim-airline.git'
"Plug 'https://github.com/jiangmiao/auto-pairs.git'
"Plug 'https://github.com/tpope/vim-fugitive.git'
"Plug 'https://github.com/scrooloose/nerdtree.git'
"Plug 'https://github.com/majutsushi/tagbar.git'
"Plug 'https://github.com/vim-scripts/YankRing.vim.git'
"Plug 'https://github.com/joequery/Stupid-EasyMotion.git'
"Plug 'https://github.com/godlygeek/tabular.git'
"Plug 'https://github.com/scrooloose/nerdcommenter.git'
"Plug 'https://github.com/sjl/gundo.vim.git'
"Plug 'https://github.com/nathanaelkane/vim-indent-guides.git'
"Plug 'https://github.com/vim-airline/vim-airline-themes.git'
"Plug 'https://github.com/henrik/vim-markdown-preview'
"Plug 'https://github.com/jeaye/color_coded.git'
Plug 'dense-analysis/ale'
"Plug 'https://github.com/airblade/vim-gitgutter'
call plug#end()
"
""vim airline status bar
"set laststatus=2
"let g:airline_theme='raven'
"let g:airline_powerline_fonts = 1
"
"
""yankring options
"let g:yankring_history_dir = '~/.vim/plugged/YankRing.vim'
"
"nmap tb :TagbarOpen fj<CR>
"nmap ttb :TagbarToggle<CR>
"nmap yr :YRShow<CR>
"nmap gu :GundoToggle<CR>

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1

set wildmode=longest,list,full
set wildmenu

" macro to fill out a header file
iab hguard #ifndef TODO<CR>#define TODO<Esc>3o<Esc>o#endif // TODO<CR><Esc>4ko

