" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
	filetype plugin indent on
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif " remember place
endif


function! AddNewlineEOF()
   " if the last line is not an empty line
    if getline('$') !~ "^$"
        " append an empty line after the last line
        call append(line('$'), '')
    endif
endfunction


" strip trailing whitespace when saving
autocmd BufWritePre * %s/\s\+$//e
autocmd BufWritePre * call AddNewlineEOF()


"colorscheme solarized


" there are 2 flags to do syntax
" so conditionally choose one
if !exists("g:syntax_on")
    syntax enable
endif


set number "set all line numbers
set relativenumber "lines relatively numbered from current
set tabstop=4 " tabs and shifts are 4 spaces wide
set shiftwidth=4
set expandtab " expand tabs as spaces
set showmatch		" Show matching brackets.
set hlsearch " highlight searched terms
set ignorecase		" Do case insensitive matching
set smartcase  " smartcase is case insensitive, unless the search term is not
set scrolloff=50
set history=1000
set mouse=c
set lazyredraw
set ttyfast
set foldmethod=syntax
set backspace=indent,eol,start
set clipboard=unnamedplus
set autoindent
set smartindent
set pastetoggle=<F2>
set shiftround
set incsearch		" Incremental search
set viminfo+=n~/.vim/viminfo
set tags=./tags;$HOME
set completeopt=longest,menuone,preview
set wildmode=longest,list,full
set wildmenu
"set colorcolumn=80  " highlight this column number


highlight Folded ctermfg=gray ctermbg=black
highlight CursorLine ctermfg=black ctermbg=yellow
highlight CursorColumn ctermfg=black ctermbg=yellow


" <Leader>c turns on cursor tracking
nnoremap <Leader>c :set cursorcolumn! cursorline!<CR>


""vim-plug calls
call plug#begin()
Plug 'dense-analysis/ale'
call plug#end()

let g:ale_cpp_cc_options = "-std=c++23"

" macro to fill out a header file
iab hguard #ifndef TODO<CR>#define TODO<Esc>3o<Esc>o#endif // TODO<CR><Esc>4ko

