#!/usr/bin/expect -f

set pdu_password [exec cat $::env(HOME)/.ssh/pdu_password]

spawn sshpass -p $pdu_password ssh pdu

expect {
    "Session is full" {
        puts ""
        close;
        exit
    }
    ">"
}

send "read status o01\n"
sleep 0.2
expect -re "Outlet.*"

send "read status o02\n"
sleep 0.2
expect -re "Outlet.*"

send "read status o03\n"
sleep 0.2
expect -re "Outlet.*"

send "read status o04\n"
sleep 0.2
expect -re "Outlet.*"

send "sw o02 imme reboot\n"
sleep 0.2
expect -re "Outlet.*"

send "quit\r\n"
sleep 0.2
expect "Goodbye!"

close

# it doesnt really matter if you use "quit" and wait for it to close the connection and everything looks good
# you're still rate limited to 2 logins per minute

