d=$HOME/.config
b=$d/bash


# if shell is in interactive mode
if [[ "$-" = *i* ]]; then
    set -o vi  # vi movement
    shopt -s cdspell  # autocorrect directory names
    stty -ixon  # Ctrl+S does not halt terminal anymore

    # enable programmable completion features
    if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
            . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
        fi
    fi

    # set up LS colors
    if [[ -f "$d/dircolors" ]]; then
        eval $(dircolors $d/dircolors)
    else
        eval $(dircolors -b)
    fi

    shopt -s histappend
    history -a
fi


set -C  # do not clobber with redirect, require >|


[[ -f "$b/bash_vars" ]]      && source "$b/bash_vars"
[[ -f "$b/bash_alias" ]]     && source "$b/bash_alias"
[[ -f "$b/bash_env" ]]       && source "$b/bash_env"
[[ -f "$b/bash_functions" ]] && source "$b/bash_functions"

