d=$HOME/.config
b=$d/bash

[[ -d $d ]]                 && pushd $d > /dev/null
[[ -f "./dircolors" ]]      && eval $(dircolors ./dircolors) || eval $(dircolors -b)
[[ -d $b ]]                 && pushd $b > /dev/null
[[ -f "./bash_vars" ]]      && source "bash_vars"
[[ -f "./bash_alias" ]]     && source "bash_alias"
[[ -f "./bash_env" ]]       && source "bash_env"
[[ -f "./bash_functions" ]] && source "bash_functions"


popd > /dev/null
popd > /dev/null


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh_agent_thing
fi

if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh_agent_thing)"
fi


set -o vi  # vi movement
set -C  # do not clobber with redirect, require >|
shopt -s cdspell  # autocorrect directory names
